version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "typescript"
        versions: ["<5.0.0"]
      - dependency-name: "vitest"
        versions: ["<1.0.0"]